language: java
sudo: false # faster builds

jdk:
    - oraclejdk8

notifications:
    email:
        - builds@fitbur.com
    on-success: change
    on-failure: always

before_install:
    - pip install --user codecov
after_success:
    - codecov
