language: java

jdk:
    - oraclejdk8

before_install:
    - pip install --user -U pip

install:
    - pip install --user codecov
    
after_success:
    - codecov

notifications:
    email:
        - builds@fitbur.com
    on-success: change
    on-failure: always
