language: java

jdk:
  - oraclejdk8

notifications:
    email:
        - builds@fitbur.com
    on-success: change
    on-failure: always
    
before_install:
  - pip install codecov
after_success:
  - codecov
