language: java
sudo: false #faster builds

jdk:
    - oraclejdk8

notifications:
    email:
        - builds@fitbur.com
    on-success: change
    on-failure: always

before_install:
    - openssl aes-256-cbc -K $encrypted_2d3d77b456af_key -iv $encrypted_2d3d77b456af_iv -in settings.xml.enc -out settings.xml -d
    - openssl aes-256-cbc -K $encrypted_2d3d77b456af_key -iv $encrypted_2d3d77b456af_iv -in secring.gpg.enc -out secring.gpg -d
    - openssl aes-256-cbc -K $encrypted_2d3d77b456af_key -iv $encrypted_2d3d77b456af_iv -in pubring.gpg.enc -out pubring.gpg -d
    - pip install --user codecov

install:
    - mvn install --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - mvn test --settings settings.xml -B
    
after_success:
    - codecov
