sudo: true

language: java

jdk:
- oraclejdk8

notifications:
  email:
  - builds@fitbur.com
  on-success: change
  on-failure: always

cache:
    apt: true
    directories:
        - $HOME/.m2

before_install:
    - openssl aes-256-cbc -K $encrypted_2d3d77b456af_key -iv $encrypted_2d3d77b456af_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - sudo apt-get install -y gnupg2
    - pip install --user codecov

install:
    - mvn install --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - mvn test --settings settings.xml -B

after_success:
    - codecov
    - "[[ $TRAVIS_BRANCH == \"develop\" ]] && { sh ./develop.sh ; };"
    - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sh ./master.sh ; };"

