language: java

jdk:
    - oraclejdk8

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        - builds@fitbur.com
    on-success: change
    on-failure: always
